// Code generated by goyacc -o comp_y.go -p comp comp.y. DO NOT EDIT.

//line comp.y:2

package express

import __yyfmt__ "fmt"

//line comp.y:3

import (
	"fmt"
	"math/big"
)

//line comp.y:12
type compSymType struct {
	yys int
	num *big.Rat
}

const NUM = 57346

var compToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'('",
	"')'",
	"NUM",
}
var compStatenames = [...]string{}

const compEofCode = 1
const compErrCode = 2
const compInitialStackSize = 16

//line comp.y:68

//line yacctab:1
var compExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const compPrivate = 57344

const compLast = 23

var compAct = [...]int{

	7, 4, 5, 2, 21, 9, 6, 8, 12, 13,
	9, 1, 8, 16, 3, 19, 20, 17, 18, 14,
	15, 10, 11,
}
var compPact = [...]int{

	-3, -1000, -1000, 17, -3, -3, 13, -1000, -1000, -3,
	2, 2, -1000, -1000, 2, 2, -5, 13, 13, -1000,
	-1000, -1000,
}
var compPgo = [...]int{

	0, 3, 14, 6, 0, 11,
}
var compR1 = [...]int{

	0, 5, 1, 1, 1, 2, 2, 2, 3, 3,
	3, 4, 4,
}
var compR2 = [...]int{

	0, 1, 1, 2, 2, 1, 3, 3, 1, 3,
	3, 1, 3,
}
var compChk = [...]int{

	-1000, -5, -1, -2, 4, 5, -3, -4, 10, 8,
	4, 5, -1, -1, 6, 7, -1, -3, -3, -4,
	-4, 9,
}
var compDef = [...]int{

	0, -2, 1, 2, 0, 0, 5, 8, 11, 0,
	0, 0, 3, 4, 0, 0, 0, 6, 7, 9,
	10, 12,
}
var compTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	8, 9, 6, 4, 3, 5, 3, 7,
}
var compTok2 = [...]int{

	2, 3, 10,
}
var compTok3 = [...]int{
	0,
}

var compErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	compDebug        = 0
	compErrorVerbose = false
)

type compLexer interface {
	Lex(lval *compSymType) int
	Error(s string)
}

type compParser interface {
	Parse(compLexer) int
	Lookahead() int
}

type compParserImpl struct {
	lval  compSymType
	stack [compInitialStackSize]compSymType
	char  int
}

func (p *compParserImpl) Lookahead() int {
	return p.char
}

func compNewParser() compParser {
	return &compParserImpl{}
}

const compFlag = -1000

func compTokname(c int) string {
	if c >= 1 && c-1 < len(compToknames) {
		if compToknames[c-1] != "" {
			return compToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func compStatname(s int) string {
	if s >= 0 && s < len(compStatenames) {
		if compStatenames[s] != "" {
			return compStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func compErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !compErrorVerbose {
		return "syntax error"
	}

	for _, e := range compErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + compTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := compPact[state]
	for tok := TOKSTART; tok-1 < len(compToknames); tok++ {
		if n := base + tok; n >= 0 && n < compLast && compChk[compAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if compDef[state] == -2 {
		i := 0
		for compExca[i] != -1 || compExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; compExca[i] >= 0; i += 2 {
			tok := compExca[i]
			if tok < TOKSTART || compExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if compExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += compTokname(tok)
	}
	return res
}

func complex1(lex compLexer, lval *compSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = compTok1[0]
		goto out
	}
	if char < len(compTok1) {
		token = compTok1[char]
		goto out
	}
	if char >= compPrivate {
		if char < compPrivate+len(compTok2) {
			token = compTok2[char-compPrivate]
			goto out
		}
	}
	for i := 0; i < len(compTok3); i += 2 {
		token = compTok3[i+0]
		if token == char {
			token = compTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = compTok2[1] /* unknown char */
	}
	if compDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", compTokname(token), uint(char))
	}
	return char, token
}

func compParse(complex compLexer) int {
	return compNewParser().Parse(complex)
}

func (comprcvr *compParserImpl) Parse(complex compLexer) int {
	var compn int
	var compVAL compSymType
	var compDollar []compSymType
	_ = compDollar // silence set and not used
	compS := comprcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	compstate := 0
	comprcvr.char = -1
	comptoken := -1 // comprcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		compstate = -1
		comprcvr.char = -1
		comptoken = -1
	}()
	compp := -1
	goto compstack

ret0:
	return 0

ret1:
	return 1

compstack:
	/* put a state and value onto the stack */
	if compDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", compTokname(comptoken), compStatname(compstate))
	}

	compp++
	if compp >= len(compS) {
		nyys := make([]compSymType, len(compS)*2)
		copy(nyys, compS)
		compS = nyys
	}
	compS[compp] = compVAL
	compS[compp].yys = compstate

compnewstate:
	compn = compPact[compstate]
	if compn <= compFlag {
		goto compdefault /* simple state */
	}
	if comprcvr.char < 0 {
		comprcvr.char, comptoken = complex1(complex, &comprcvr.lval)
	}
	compn += comptoken
	if compn < 0 || compn >= compLast {
		goto compdefault
	}
	compn = compAct[compn]
	if compChk[compn] == comptoken { /* valid shift */
		comprcvr.char = -1
		comptoken = -1
		compVAL = comprcvr.lval
		compstate = compn
		if Errflag > 0 {
			Errflag--
		}
		goto compstack
	}

compdefault:
	/* default state action */
	compn = compDef[compstate]
	if compn == -2 {
		if comprcvr.char < 0 {
			comprcvr.char, comptoken = complex1(complex, &comprcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if compExca[xi+0] == -1 && compExca[xi+1] == compstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			compn = compExca[xi+0]
			if compn < 0 || compn == comptoken {
				break
			}
		}
		compn = compExca[xi+1]
		if compn < 0 {
			goto ret0
		}
	}
	if compn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			complex.Error(compErrorMessage(compstate, comptoken))
			Nerrs++
			if compDebug >= 1 {
				__yyfmt__.Printf("%s", compStatname(compstate))
				__yyfmt__.Printf(" saw %s\n", compTokname(comptoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for compp >= 0 {
				compn = compPact[compS[compp].yys] + compErrCode
				if compn >= 0 && compn < compLast {
					compstate = compAct[compn] /* simulate a shift of "error" */
					if compChk[compstate] == compErrCode {
						goto compstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if compDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", compS[compp].yys)
				}
				compp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if compDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", compTokname(comptoken))
			}
			if comptoken == compEofCode {
				goto ret1
			}
			comprcvr.char = -1
			comptoken = -1
			goto compnewstate /* try again in the same state */
		}
	}

	/* reduction by production compn */
	if compDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", compn, compStatname(compstate))
	}

	compnt := compn
	comppt := compp
	_ = comppt // guard against "declared and not used"

	compp -= compR2[compn]
	// compp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if compp+1 >= len(compS) {
		nyys := make([]compSymType, len(compS)*2)
		copy(nyys, compS)
		compS = nyys
	}
	compVAL = compS[compp+1]

	/* consult goto table to find next state */
	compn = compR1[compn]
	compg := compPgo[compn]
	compj := compg + compS[compp].yys + 1

	if compj >= compLast {
		compstate = compAct[compg]
	} else {
		compstate = compAct[compj]
		if compChk[compstate] != -compn {
			compstate = compAct[compg]
		}
	}
	// dummy call; replaced with literal code
	switch compnt {

	case 1:
		compDollar = compS[comppt-1 : comppt+1]
//line comp.y:25
		{

		}
	case 3:
		compDollar = compS[comppt-2 : comppt+1]
//line comp.y:31
		{
			compVAL.num = compDollar[2].num
		}
	case 4:
		compDollar = compS[comppt-2 : comppt+1]
//line comp.y:35
		{
			compVAL.num = compDollar[2].num.Neg(compDollar[2].num)
		}
	case 6:
		compDollar = compS[comppt-3 : comppt+1]
//line comp.y:42
		{
			compVAL.num = compDollar[1].num.Add(compDollar[1].num, compDollar[3].num)
		}
	case 7:
		compDollar = compS[comppt-3 : comppt+1]
//line comp.y:46
		{
			compVAL.num = compDollar[1].num.Sub(compDollar[1].num, compDollar[3].num)
		}
	case 9:
		compDollar = compS[comppt-3 : comppt+1]
//line comp.y:53
		{
			compVAL.num = compDollar[1].num.Mul(compDollar[1].num, compDollar[3].num)
		}
	case 10:
		compDollar = compS[comppt-3 : comppt+1]
//line comp.y:57
		{
			compVAL.num = compDollar[1].num.Quo(compDollar[1].num, compDollar[3].num)
		}
	case 12:
		compDollar = compS[comppt-3 : comppt+1]
//line comp.y:64
		{
			compVAL.num = compDollar[2].num
		}
	}
	goto compstack /* stack new state and value */
}
