// Code generated by goyacc -o cond_y.go -p cond cond.y. DO NOT EDIT.

//line cond.y:2

package express

import __yyfmt__ "fmt"

//line cond.y:3

import (
	"fmt"
	"math/rat"
)

//line cond.y:12
type condSymType struct {
	yys int
	num *big.Rat
}

const NUM = 57346

var condToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"'>'",
	"'<'",
	"'='",
	"'&'",
	"'|'",
	"'('",
	"')'",
	"NUM",
}
var condStatenames = [...]string{}

const condEofCode = 1
const condErrCode = 2
const condInitialStackSize = 16

//line cond.y:62
